# Generated by Django 4.2.5 on 2023-10-07 02:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lesson.basemodel')),
                ('content', models.CharField(max_length=200)),
            ],
            bases=('lesson.basemodel', models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lesson.basemodel')),
                ('question_text', models.CharField(max_length=200, verbose_name='question')),
                ('type', models.CharField(choices=[('MULTIPLE', 'Multiple Answer'), ('SINGLE', 'Single Answer')], max_length=15)),
                ('f_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
            ],
            bases=('lesson.basemodel', models.Model),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lesson.basemodel')),
                ('choice_text', models.CharField(max_length=100, verbose_name='choice')),
                ('is_answer', models.BooleanField(default=False, verbose_name='is answer')),
                ('f_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.question')),
            ],
            bases=('lesson.basemodel', models.Model),
        ),
    ]
