# Generated by Django 4.2.5 on 2023-10-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='f_lesson',
            new_name='lessons',
        ),
    ]
