# Generated by Django 4.2.5 on 2023-10-07 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_rename_f_lesson_question_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='f_question',
        ),
        migrations.AddField(
            model_name='choice',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lesson.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lessons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='lesson.lesson'),
        ),
    ]
