# Generated by Django 4.2.5 on 2023-10-07 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_remove_choice_f_question_choice_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lesson.question'),
        ),
    ]
