# Generated by Django 4.2.5 on 2023-10-07 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_remove_question_type_alter_choice_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
    ]
