# Generated by Django 4.2.5 on 2023-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_alter_choice_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='passing_score',
            field=models.IntegerField(default=0),
        ),
    ]
